# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'GCS_update1.ui'
#
# Created by: PyQt5 UI code generator 5.8
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1920, 1080)
        MainWindow.setMaximumSize(QtCore.QSize(1920, 1080))
        MainWindow.setStyleSheet("")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.leftMenu = QtWidgets.QWidget(self.centralwidget)
        self.leftMenu.setGeometry(QtCore.QRect(0, 0, 370, 1080))
        self.leftMenu.setMinimumSize(QtCore.QSize(370, 1080))
        self.leftMenu.setObjectName("leftMenu")
        self.layoutWidget = QtWidgets.QWidget(self.leftMenu)
        self.layoutWidget.setGeometry(QtCore.QRect(0, 0, 401, 1077))
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        spacerItem = QtWidgets.QSpacerItem(370, 325, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.verticalLayout.addItem(spacerItem)
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setSizeConstraint(QtWidgets.QLayout.SetFixedSize)
        self.gridLayout.setHorizontalSpacing(25)
        self.gridLayout.setVerticalSpacing(85)
        self.gridLayout.setObjectName("gridLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setSizeConstraint(QtWidgets.QLayout.SetFixedSize)
        self.horizontalLayout.setSpacing(12)
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem1 = QtWidgets.QSpacerItem(50, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.temp_img = QtWidgets.QLabel(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(5)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.temp_img.sizePolicy().hasHeightForWidth())
        self.temp_img.setSizePolicy(sizePolicy)
        self.temp_img.setMinimumSize(QtCore.QSize(50, 60))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.temp_img.setFont(font)
        self.temp_img.setStyleSheet("")
        self.temp_img.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.temp_img.setObjectName("temp_img")
        self.horizontalLayout.addWidget(self.temp_img)
        self.temp = QtWidgets.QLabel(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.temp.sizePolicy().hasHeightForWidth())
        self.temp.setSizePolicy(sizePolicy)
        self.temp.setMinimumSize(QtCore.QSize(50, 40))
        self.temp.setMaximumSize(QtCore.QSize(50, 40))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(16)
        self.temp.setFont(font)
        self.temp.setStyleSheet("")
        self.temp.setTextFormat(QtCore.Qt.AutoText)
        self.temp.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.temp.setObjectName("temp")
        self.horizontalLayout.addWidget(self.temp)
        self.gridLayout.addLayout(self.horizontalLayout, 0, 0, 1, 1)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setSpacing(12)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.pres_img = QtWidgets.QLabel(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pres_img.sizePolicy().hasHeightForWidth())
        self.pres_img.setSizePolicy(sizePolicy)
        self.pres_img.setMinimumSize(QtCore.QSize(50, 60))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.pres_img.setFont(font)
        self.pres_img.setStyleSheet("")
        self.pres_img.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.pres_img.setObjectName("pres_img")
        self.horizontalLayout_4.addWidget(self.pres_img)
        self.pres = QtWidgets.QLabel(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pres.sizePolicy().hasHeightForWidth())
        self.pres.setSizePolicy(sizePolicy)
        self.pres.setMinimumSize(QtCore.QSize(50, 40))
        self.pres.setMaximumSize(QtCore.QSize(50, 40))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(16)
        self.pres.setFont(font)
        self.pres.setStyleSheet("")
        self.pres.setTextFormat(QtCore.Qt.AutoText)
        self.pres.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.pres.setObjectName("pres")
        self.horizontalLayout_4.addWidget(self.pres)
        spacerItem2 = QtWidgets.QSpacerItem(50, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem2)
        self.gridLayout.addLayout(self.horizontalLayout_4, 0, 1, 1, 1)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setSpacing(12)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        spacerItem3 = QtWidgets.QSpacerItem(50, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem3)
        self.bot_img = QtWidgets.QLabel(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.bot_img.sizePolicy().hasHeightForWidth())
        self.bot_img.setSizePolicy(sizePolicy)
        self.bot_img.setMinimumSize(QtCore.QSize(50, 60))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.bot_img.setFont(font)
        self.bot_img.setStyleSheet("")
        self.bot_img.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.bot_img.setObjectName("bot_img")
        self.horizontalLayout_2.addWidget(self.bot_img)
        self.bot = QtWidgets.QLabel(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.bot.sizePolicy().hasHeightForWidth())
        self.bot.setSizePolicy(sizePolicy)
        self.bot.setMinimumSize(QtCore.QSize(50, 40))
        self.bot.setMaximumSize(QtCore.QSize(50, 40))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(16)
        self.bot.setFont(font)
        self.bot.setStyleSheet("")
        self.bot.setTextFormat(QtCore.Qt.AutoText)
        self.bot.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.bot.setObjectName("bot")
        self.horizontalLayout_2.addWidget(self.bot)
        self.gridLayout.addLayout(self.horizontalLayout_2, 1, 0, 1, 1)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setSpacing(12)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.spin_img = QtWidgets.QLabel(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.spin_img.sizePolicy().hasHeightForWidth())
        self.spin_img.setSizePolicy(sizePolicy)
        self.spin_img.setMinimumSize(QtCore.QSize(50, 60))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.spin_img.setFont(font)
        self.spin_img.setStyleSheet("")
        self.spin_img.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.spin_img.setObjectName("spin_img")
        self.horizontalLayout_5.addWidget(self.spin_img)
        self.spin = QtWidgets.QLabel(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.spin.sizePolicy().hasHeightForWidth())
        self.spin.setSizePolicy(sizePolicy)
        self.spin.setMinimumSize(QtCore.QSize(50, 40))
        self.spin.setMaximumSize(QtCore.QSize(50, 40))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(16)
        self.spin.setFont(font)
        self.spin.setStyleSheet("")
        self.spin.setTextFormat(QtCore.Qt.AutoText)
        self.spin.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.spin.setObjectName("spin")
        self.horizontalLayout_5.addWidget(self.spin)
        spacerItem4 = QtWidgets.QSpacerItem(50, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem4)
        self.gridLayout.addLayout(self.horizontalLayout_5, 1, 1, 1, 1)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setSpacing(12)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        spacerItem5 = QtWidgets.QSpacerItem(50, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem5)
        self.pitch_img = QtWidgets.QLabel(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pitch_img.sizePolicy().hasHeightForWidth())
        self.pitch_img.setSizePolicy(sizePolicy)
        self.pitch_img.setMinimumSize(QtCore.QSize(50, 60))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.pitch_img.setFont(font)
        self.pitch_img.setStyleSheet("")
        self.pitch_img.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.pitch_img.setObjectName("pitch_img")
        self.horizontalLayout_3.addWidget(self.pitch_img)
        self.pitch = QtWidgets.QLabel(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pitch.sizePolicy().hasHeightForWidth())
        self.pitch.setSizePolicy(sizePolicy)
        self.pitch.setMinimumSize(QtCore.QSize(50, 40))
        self.pitch.setMaximumSize(QtCore.QSize(50, 40))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(16)
        self.pitch.setFont(font)
        self.pitch.setStyleSheet("")
        self.pitch.setTextFormat(QtCore.Qt.AutoText)
        self.pitch.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.pitch.setObjectName("pitch")
        self.horizontalLayout_3.addWidget(self.pitch)
        self.gridLayout.addLayout(self.horizontalLayout_3, 2, 0, 1, 1)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setSpacing(12)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.roll_img = QtWidgets.QLabel(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.roll_img.sizePolicy().hasHeightForWidth())
        self.roll_img.setSizePolicy(sizePolicy)
        self.roll_img.setMinimumSize(QtCore.QSize(50, 60))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.roll_img.setFont(font)
        self.roll_img.setStyleSheet("")
        self.roll_img.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.roll_img.setObjectName("roll_img")
        self.horizontalLayout_6.addWidget(self.roll_img)
        self.roll = QtWidgets.QLabel(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.roll.sizePolicy().hasHeightForWidth())
        self.roll.setSizePolicy(sizePolicy)
        self.roll.setMinimumSize(QtCore.QSize(50, 40))
        self.roll.setMaximumSize(QtCore.QSize(50, 40))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(16)
        self.roll.setFont(font)
        self.roll.setStyleSheet("")
        self.roll.setTextFormat(QtCore.Qt.AutoText)
        self.roll.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.roll.setObjectName("roll")
        self.horizontalLayout_6.addWidget(self.roll)
        spacerItem6 = QtWidgets.QSpacerItem(50, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem6)
        self.gridLayout.addLayout(self.horizontalLayout_6, 2, 1, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout)
        spacerItem7 = QtWidgets.QSpacerItem(20, 80, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.verticalLayout.addItem(spacerItem7)
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setSizeConstraint(QtWidgets.QLayout.SetFixedSize)
        self.gridLayout_2.setHorizontalSpacing(25)
        self.gridLayout_2.setVerticalSpacing(45)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        spacerItem8 = QtWidgets.QSpacerItem(50, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_7.addItem(spacerItem8)
        self.gps_lat_img = QtWidgets.QLabel(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.gps_lat_img.sizePolicy().hasHeightForWidth())
        self.gps_lat_img.setSizePolicy(sizePolicy)
        self.gps_lat_img.setMinimumSize(QtCore.QSize(50, 60))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.gps_lat_img.setFont(font)
        self.gps_lat_img.setStyleSheet("")
        self.gps_lat_img.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.gps_lat_img.setObjectName("gps_lat_img")
        self.horizontalLayout_7.addWidget(self.gps_lat_img)
        self.gps_lat = QtWidgets.QLabel(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.gps_lat.sizePolicy().hasHeightForWidth())
        self.gps_lat.setSizePolicy(sizePolicy)
        self.gps_lat.setMinimumSize(QtCore.QSize(50, 40))
        self.gps_lat.setMaximumSize(QtCore.QSize(50, 40))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(16)
        self.gps_lat.setFont(font)
        self.gps_lat.setStyleSheet("")
        self.gps_lat.setTextFormat(QtCore.Qt.AutoText)
        self.gps_lat.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.gps_lat.setObjectName("gps_lat")
        self.horizontalLayout_7.addWidget(self.gps_lat)
        self.gridLayout_2.addLayout(self.horizontalLayout_7, 0, 0, 1, 1)
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.gps_long_img = QtWidgets.QLabel(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.gps_long_img.sizePolicy().hasHeightForWidth())
        self.gps_long_img.setSizePolicy(sizePolicy)
        self.gps_long_img.setMinimumSize(QtCore.QSize(50, 60))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.gps_long_img.setFont(font)
        self.gps_long_img.setStyleSheet("")
        self.gps_long_img.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.gps_long_img.setObjectName("gps_long_img")
        self.horizontalLayout_8.addWidget(self.gps_long_img)
        self.gps_long = QtWidgets.QLabel(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.gps_long.sizePolicy().hasHeightForWidth())
        self.gps_long.setSizePolicy(sizePolicy)
        self.gps_long.setMinimumSize(QtCore.QSize(50, 40))
        self.gps_long.setMaximumSize(QtCore.QSize(50, 40))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(16)
        self.gps_long.setFont(font)
        self.gps_long.setStyleSheet("")
        self.gps_long.setTextFormat(QtCore.Qt.AutoText)
        self.gps_long.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.gps_long.setObjectName("gps_long")
        self.horizontalLayout_8.addWidget(self.gps_long)
        spacerItem9 = QtWidgets.QSpacerItem(50, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_8.addItem(spacerItem9)
        self.gridLayout_2.addLayout(self.horizontalLayout_8, 0, 1, 1, 1)
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_9.setSizeConstraint(QtWidgets.QLayout.SetMinimumSize)
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        spacerItem10 = QtWidgets.QSpacerItem(50, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_9.addItem(spacerItem10)
        self.gps_alt_img = QtWidgets.QLabel(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.gps_alt_img.sizePolicy().hasHeightForWidth())
        self.gps_alt_img.setSizePolicy(sizePolicy)
        self.gps_alt_img.setMinimumSize(QtCore.QSize(50, 60))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.gps_alt_img.setFont(font)
        self.gps_alt_img.setStyleSheet("")
        self.gps_alt_img.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.gps_alt_img.setObjectName("gps_alt_img")
        self.horizontalLayout_9.addWidget(self.gps_alt_img)
        self.gps_alt = QtWidgets.QLabel(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.gps_alt.sizePolicy().hasHeightForWidth())
        self.gps_alt.setSizePolicy(sizePolicy)
        self.gps_alt.setMinimumSize(QtCore.QSize(50, 40))
        self.gps_alt.setMaximumSize(QtCore.QSize(50, 40))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(16)
        self.gps_alt.setFont(font)
        self.gps_alt.setStyleSheet("")
        self.gps_alt.setTextFormat(QtCore.Qt.AutoText)
        self.gps_alt.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.gps_alt.setObjectName("gps_alt")
        self.horizontalLayout_9.addWidget(self.gps_alt)
        self.gridLayout_2.addLayout(self.horizontalLayout_9, 1, 0, 1, 1)
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.gps_sats_img = QtWidgets.QLabel(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.gps_sats_img.sizePolicy().hasHeightForWidth())
        self.gps_sats_img.setSizePolicy(sizePolicy)
        self.gps_sats_img.setMinimumSize(QtCore.QSize(50, 60))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.gps_sats_img.setFont(font)
        self.gps_sats_img.setStyleSheet("")
        self.gps_sats_img.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.gps_sats_img.setObjectName("gps_sats_img")
        self.horizontalLayout_10.addWidget(self.gps_sats_img)
        self.gps_sats = QtWidgets.QLabel(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.gps_sats.sizePolicy().hasHeightForWidth())
        self.gps_sats.setSizePolicy(sizePolicy)
        self.gps_sats.setMinimumSize(QtCore.QSize(50, 40))
        self.gps_sats.setMaximumSize(QtCore.QSize(50, 40))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(16)
        self.gps_sats.setFont(font)
        self.gps_sats.setStyleSheet("")
        self.gps_sats.setTextFormat(QtCore.Qt.AutoText)
        self.gps_sats.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.gps_sats.setObjectName("gps_sats")
        self.horizontalLayout_10.addWidget(self.gps_sats)
        spacerItem11 = QtWidgets.QSpacerItem(50, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_10.addItem(spacerItem11)
        self.gridLayout_2.addLayout(self.horizontalLayout_10, 1, 1, 1, 1)
        self.gridLayout_2.setColumnMinimumWidth(0, 40)
        self.gridLayout_2.setColumnMinimumWidth(1, 40)
        self.verticalLayout.addLayout(self.gridLayout_2)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1920, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.temp_img.setText(_translate("MainWindow", "0"))
        self.temp.setText(_translate("MainWindow", "0"))
        self.pres_img.setText(_translate("MainWindow", "0"))
        self.pres.setText(_translate("MainWindow", "0"))
        self.bot_img.setText(_translate("MainWindow", "0"))
        self.bot.setText(_translate("MainWindow", "0"))
        self.spin_img.setText(_translate("MainWindow", "0"))
        self.spin.setText(_translate("MainWindow", "0"))
        self.pitch_img.setText(_translate("MainWindow", "0"))
        self.pitch.setText(_translate("MainWindow", "0"))
        self.roll_img.setText(_translate("MainWindow", "0"))
        self.roll.setText(_translate("MainWindow", "0"))
        self.gps_lat_img.setText(_translate("MainWindow", "0"))
        self.gps_lat.setText(_translate("MainWindow", "0"))
        self.gps_long_img.setText(_translate("MainWindow", "0"))
        self.gps_long.setText(_translate("MainWindow", "0"))
        self.gps_alt_img.setText(_translate("MainWindow", "0"))
        self.gps_alt.setText(_translate("MainWindow", "0"))
        self.gps_sats_img.setText(_translate("MainWindow", "0"))
        self.gps_sats.setText(_translate("MainWindow", "0"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

